VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


  config.vm.define :master do |node01|
    node01.vm.hostname = "master"
    node01.vm.network :private_network, ip: "192.168.56.101"
    node01.vm.box = "bento/ubuntu-18.04"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    end
  end
  config.vm.define :worker1 do |node02|
    node02.vm.hostname = "worker1"
    node02.vm.network :private_network, ip: "192.168.56.102"
    node02.vm.box = "bento/ubuntu-18.04"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    end
  end
  config.vm.define :worker2 do |node03|
    node03.vm.hostname = "worker2"
    node03.vm.network :private_network, ip: "192.168.56.103"
    node03.vm.box = "bento/ubuntu-18.04"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    end
  end
end
