VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


  config.vm.define :master do |node01|
    node01.vm.hostname = "master"
    node01.vm.network :private_network, ip: "192.168.56.101"
    node01.vm.box = "bento/ubuntu-18.04"
    node01.vm.synced_folder ".", "/vagrant", disabled: true
    node01.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
    node01.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    end
    node01.vm.provision :file do |file|
      file.source = "./kubernetes.list"
      file.destination = "/home/vagrant/kubernetes.list"
    end
    node01.vm.provision :file do |file|
      file.source = "./k8s-installer.sh"
      file.destination = "/home/vagrant/k8s-installer.sh"
    end
    node01.vm.provision "shell", inline: <<-SHELL
      sudo sh /home/vagrant/k8s-installer.sh
    SHELL
  end
end
